homeassistant:
  customize:
    sun.sun:
      icon: 'mdi:weather-sunny'
    sensor.dark_sky_humidity:
      icon: 'mdi:water-percent'
      friendly_name: Humidity
    sensor.dark_sky_temperature:
      icon: 'mdi:thermometer'
      friendly_name: Temperature
    sensor.dark_sky_summary:
      icon: 'mdi:leaf'
      friendly_name: Conditions
    sensor.dark_sky_cloud_coverage:
      friendly_name: Cloud Coverage
    sensor.dark_sky_daily_high_temperature:
      hidden: true
    sensor.dark_sky_daily_low_temperature:
      hidden: true
    sensor.dark_sky_daily_summary:
      hidden: true
    sensor.dark_sky_hourly_summary:
      hidden: true

group:
  Outdoors:
    - sensor.dark_sky_summary
    - sun.sun
    - sensor.dark_sky_temperature
    - sensor.dark_sky_humidity
    - sensor.dark_sky_cloud_coverage

sensor:
  - platform: darksky
    api_key: ef478f7fe98473724dd77342518ff1bf
    update_interval:
      minutes: 10
    monitored_conditions:
      - summary
      - temperature
      - humidity
      - hourly_summary
      - daily_summary
      - cloud_cover