homeassistant:
  customize:
    sensor.glances_sensor_cpu_load:
      friendly_name: CPU Load
      icon: 'mdi:memory'
    sensor.glances_sensor_disk_use:
      friendly_name: Disk
      icon: 'mdi:harddisk'
    sensor.glances_sensor_ram_use:
      friendly_name: Memory
      icon: 'mdi:server'

group:
  Server:
    - sensor.glances_sensor_cpu_load
    - sensor.glances_sensor_disk_use
    - sensor.glances_sensor_ram_use

sensor:
  - platform: glances
    name: Glances sensor
    host: localhost
    port: 61208
    resources:
      - disk_use_percent
      - memory_use_percent
      - processor_load